/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import SystemAndMain.HelioStoreSystem;
import devicehasA.Mouse;
import heliostoreInheritance.Desktop;

/**
 *
 * @author didem
 */
public class DesktopFrame extends javax.swing.JFrame {

    /**
     * Creates new form AddFrame
     */
    public DesktopFrame() {
        initComponents();
        setLocationRelativeTo(null);
        setSize(350, 500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mousebg = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ssizetxt = new javax.swing.JTextField();
        brandtxt = new javax.swing.JTextField();
        snotxt = new javax.swing.JTextField();
        weighttxt = new javax.swing.JTextField();
        yeartxt = new javax.swing.JTextField();
        pricetxt = new javax.swing.JTextField();
        colortxt = new javax.swing.JTextField();
        addbtn = new javax.swing.JButton();
        towertxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        wiredr = new javax.swing.JRadioButton();
        wirelessr = new javax.swing.JRadioButton();
        closebtn = new javax.swing.JButton();
        emptylabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        versiontxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Serial No:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel2.setText("Brand:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel3.setText("Screen Size:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel4.setText("Weight:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel5.setText("Year:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel6.setText("Price:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel7.setText("Color:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));
        getContentPane().add(ssizetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 180, -1));

        brandtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brandtxtActionPerformed(evt);
            }
        });
        getContentPane().add(brandtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 180, -1));

        snotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snotxtActionPerformed(evt);
            }
        });
        getContentPane().add(snotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 180, -1));
        getContentPane().add(weighttxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 180, -1));
        getContentPane().add(yeartxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 180, -1));

        pricetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pricetxtActionPerformed(evt);
            }
        });
        getContentPane().add(pricetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 180, -1));
        getContentPane().add(colortxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 180, -1));

        addbtn.setText("Add");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });
        getContentPane().add(addbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 170, -1));
        getContentPane().add(towertxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 180, -1));

        jLabel8.setText("Tower Type:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jLabel9.setText("Mouse:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        mousebg.add(wiredr);
        wiredr.setSelected(true);
        wiredr.setText("Wired");
        getContentPane().add(wiredr, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, -1));

        mousebg.add(wirelessr);
        wirelessr.setText("Wireless");
        wirelessr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wirelessrActionPerformed(evt);
            }
        });
        getContentPane().add(wirelessr, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, -1, -1));

        closebtn.setText("Close");
        closebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebtnActionPerformed(evt);
            }
        });
        getContentPane().add(closebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, -1, -1));

        emptylabel.setText(" ");
        getContentPane().add(emptylabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 270, 40));

        jLabel10.setText("Version:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));
        getContentPane().add(versiontxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 180, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pricetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pricetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pricetxtActionPerformed

    private void wirelessrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wirelessrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wirelessrActionPerformed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed

        Mouse m = new Mouse();
        String sno = "";

        if (brandtxt.getText().equals("") || colortxt.getText().equals("") || pricetxt.getText().equals("")
                || towertxt.getText().equals("") || snotxt.getText().equals("") || ssizetxt.getText().equals("")
                || yeartxt.getText().equals("") || weighttxt.getText().equals("") || versiontxt.getText().equals("")) {
            emptylabel.setText("Please fill the necessary fields!!");
        } else {
            sno = snotxt.getText();
            if (!HelioStoreSystem.checkSerialNo(sno)) {
                String brand = brandtxt.getText();
                double ssize = Double.parseDouble(ssizetxt.getText());
                double weight = Double.parseDouble(weighttxt.getText());
                String version = versiontxt.getText();
                int year = Integer.parseInt(yeartxt.getText());
                double price = Double.parseDouble(pricetxt.getText());
                String color = colortxt.getText();
                String tower = towertxt.getText();
                if (wiredr.isSelected()) {
                    m.setWire(true);
                } else {
                    m.setWire(false);
                }
                Desktop desk = new Desktop(sno, brand, ssize, weight, year, color, price, version, tower, m);
                HelioStoreSystem.list.add(desk);
                emptylabel.setText("Added");
            } else{
                emptylabel.setText("This serialno already exist!");
            }

        }
    }//GEN-LAST:event_addbtnActionPerformed

    private void brandtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brandtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brandtxtActionPerformed

    private void snotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_snotxtActionPerformed

    private void closebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebtnActionPerformed
        dispose();
    }//GEN-LAST:event_closebtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JTextField brandtxt;
    private javax.swing.JButton closebtn;
    private javax.swing.JTextField colortxt;
    private javax.swing.JLabel emptylabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.ButtonGroup mousebg;
    private javax.swing.JTextField pricetxt;
    private javax.swing.JTextField snotxt;
    private javax.swing.JTextField ssizetxt;
    private javax.swing.JTextField towertxt;
    private javax.swing.JTextField versiontxt;
    private javax.swing.JTextField weighttxt;
    private javax.swing.JRadioButton wiredr;
    private javax.swing.JRadioButton wirelessr;
    private javax.swing.JTextField yeartxt;
    // End of variables declaration//GEN-END:variables
}
