/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import SystemAndMain.HelioStoreSystem;

/**
 *
 * @author didem
 */
public class MainFrame extends javax.swing.JFrame {

    DesktopFrame d = new DesktopFrame();
    NotebookFrame n = new NotebookFrame();
    SmartphoneFrame s = new SmartphoneFrame();
    SearchandRemoveFrame snr = new SearchandRemoveFrame();
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setLocationRelativeTo(null);
        setSize(600, 450);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtarea = new javax.swing.JTextArea();
        displaybtn = new javax.swing.JButton();
        addbtn = new javax.swing.JButton();
        closebtn = new javax.swing.JButton();
        cmbbox = new javax.swing.JComboBox<>();
        searchandremovebtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtarea.setColumns(20);
        txtarea.setRows(5);
        jScrollPane2.setViewportView(txtarea);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 270));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 450, 270));

        displaybtn.setText("Display");
        displaybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displaybtnActionPerformed(evt);
            }
        });
        getContentPane().add(displaybtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 140, -1));

        addbtn.setText("Add");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });
        getContentPane().add(addbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 80, -1));

        closebtn.setText("Close");
        closebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebtnActionPerformed(evt);
            }
        });
        getContentPane().add(closebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 160, -1));

        cmbbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Smartphone", "Desktop", "Notebook" }));
        cmbbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbboxActionPerformed(evt);
            }
        });
        getContentPane().add(cmbbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 170, -1));

        searchandremovebtn.setText("Search and Remove");
        searchandremovebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchandremovebtnActionPerformed(evt);
            }
        });
        getContentPane().add(searchandremovebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 260, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbboxActionPerformed

    private void closebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebtnActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_closebtnActionPerformed

    private void displaybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displaybtnActionPerformed
        // TODO add your handling code here:
        if(HelioStoreSystem.list.isEmpty()){
            txtarea.setText("The System is empty!!");
        }else{
            txtarea.setText(HelioStoreSystem.displayDevice());                   
        }               
    }//GEN-LAST:event_displaybtnActionPerformed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        // TODO add your handling code here:
        String device = (String) cmbbox.getSelectedItem();
        
        if(device.equalsIgnoreCase("smartphone")){
            s.setVisible(true);
        }else if(device.equalsIgnoreCase("desktop")){
            d.setVisible(true);
        }else
            n.setVisible(true);
        
    }//GEN-LAST:event_addbtnActionPerformed

    private void searchandremovebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchandremovebtnActionPerformed
        snr.setVisible(true);
    }//GEN-LAST:event_searchandremovebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JButton closebtn;
    private javax.swing.JComboBox<String> cmbbox;
    private javax.swing.JButton displaybtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton searchandremovebtn;
    private javax.swing.JTextArea txtarea;
    // End of variables declaration//GEN-END:variables
}
