/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import SystemAndMain.HelioStoreSystem;
import heliostoreInheritance.Devices;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;

/**
 *
 * @author didem
 */
public class SearchandRemoveFrame extends javax.swing.JFrame {

    /**
     * Creates new form SearchFrame
     */
    public SearchandRemoveFrame() {
        initComponents();
        setLocationRelativeTo(null);
        setSize(450, 500);
    }
    
    public JComboBox<String> getCombo() {
      return combo;
    }

  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtarea = new javax.swing.JTextArea();
        closebtn = new javax.swing.JButton();
        combo = new javax.swing.JComboBox<>();
        search = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        removetxt = new javax.swing.JTextField();
        emptylabel = new javax.swing.JLabel();
        removebtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtarea.setColumns(20);
        txtarea.setRows(5);
        jScrollPane1.setViewportView(txtarea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 350, 180));

        closebtn.setText("Close");
        closebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebtnActionPerformed(evt);
            }
        });
        getContentPane().add(closebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 150, -1));

        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Apple", "Samsung", "Casper", "Hp", "Dell" }));
        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });
        getContentPane().add(combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 150, -1));

        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 120, -1));

        jLabel1.setText("Enter Serial No to remove:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));
        getContentPane().add(removetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 180, 30));

        emptylabel.setText(" ");
        getContentPane().add(emptylabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 350, 50));

        removebtn.setText("Remove");
        removebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removebtnActionPerformed(evt);
            }
        });
        getContentPane().add(removebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 150, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebtnActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_closebtnActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed

        String brand = (String) combo.getSelectedItem();
        txtarea.setText(HelioStoreSystem.searchDevice(brand));
       
    }//GEN-LAST:event_searchActionPerformed

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed

    }//GEN-LAST:event_comboActionPerformed

    private void removebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removebtnActionPerformed
        // TODO add your handling code here:
        String serialno = removetxt.getText();
        
        if(HelioStoreSystem.removeDevice(serialno)){
            emptylabel.setText("Device is removed.");
        }else{
            emptylabel.setText("There is no such device!!");
        }
        
        
    }//GEN-LAST:event_removebtnActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closebtn;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JLabel emptylabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton removebtn;
    private javax.swing.JTextField removetxt;
    private javax.swing.JButton search;
    private javax.swing.JTextArea txtarea;
    // End of variables declaration//GEN-END:variables
}
